import { Container, Typography } from "@mui/material";
import { Box, styled } from "@mui/system";
import type { NextPage } from "next";
import Head from "next/head";
import theme from "../styles/theme";

const Wrapper = styled(Container)(({ theme }) => ({
  display: "flex",
  flexDirection: "column",
  alignItems: "center",
  justifyContent: "center",
}));

const HeaderWrapper = styled(Box)(({ theme }) => ({
  display: "flex",
  flexDirection: "column",
  alignItems: "center",
  justifyContent: "center",
  padding: "16px",
  backgroundColor: theme.palette.primary.main,
}));

const Header = styled(Typography)(({ theme }) => ({
  fontWeight: 500,
  color: theme.palette.text.secondary,
}));

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <HeaderWrapper>
          <Header variant="h2">This is a sample header!</Header>
        </HeaderWrapper>
        <Typography
          sx={{
            color: theme.palette.text.primary,
            textAlign: "center",
            marginTop: "32px",
          }}
        >
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nec
          massa et magna feugiat placerat. Pellentesque interdum fermentum est,
          a convallis dui feugiat vitae. Phasellus eget quam posuere, auctor
          justo vitae, pretium magna. Praesent facilisis blandit condimentum.
          Curabitur pulvinar vitae nulla ut iaculis. Praesent non iaculis est.
          In a feugiat metus. Aenean et ullamcorper arcu. Nulla semper diam vel
          scelerisque vulputate.
        </Typography>
      </Wrapper>
    </>
  );
};

export default Home;
