import { Container, Typography } from "@mui/material";
import { styled } from "@mui/system";
import type { NextPage } from "next";
import Head from "next/head";

const Wrapper = styled(Container)({
  display: "flex",
  flexDirection: "column",
  alignItems: "center",
  justifyContent: "center",
  backgroundColor: "#00b4d8",
});

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <Typography variant="h2" sx={{ fontWeight: "bold" }}>
          This is a sample text!
        </Typography>
      </Wrapper>
    </>
  );
};

export default Home;
